version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ../docker/nestjs/Dockerfile
      target: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "yarn && yarn start:dev"
    env_file:
      - ./api/.env